version: '3.9'

services:
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - flussonic
    ports:
      - "8000:8000"
    restart: always

  flussonic:
    image: flussonic/flussonic
    ports:
      - 80:80
    volumes:
      - ~/etc/flussonic:/etc/flussonic
